package turfbeat.com.navigation

object Routes {
    const val SPLASH = "splash"
    const val SIGN_IN = "sign_in"
    const val SIGN_UP = "sign_up"
    const val FORGOT_PASSWORD = "forgot_password"
    const val HOME = "home"
    const val CLUB_DIRECTORY = "clubs"
    const val CLUB_DETAIL = "clubs/{clubId}"
    const val VENUE_DIRECTORY = "venues"
    const val VENUE_DETAIL = "venues/{venueId}"
    const val PLAYER_DIRECTORY = "players"
    const val PLAYER_DETAIL = "players/{playerId}"
    const val MATCH_BOARD = "matches"
    const val MATCH_DETAIL = "matches/{matchId}"
    const val PLAYER_DASHBOARD = "player/dashboard"
    const val CLUB_DASHBOARD = "club/dashboard"
    const val VENUE_DASHBOARD = "venue/dashboard"
    const val ADMIN_DASHBOARD = "admin/dashboard"
    const val MATCH_CHAT = "chat/{matchId}"
    const val NOTIFICATIONS = "notifications"
    const val SETTINGS = "settings"
    const val ABOUT = "about"
    const val HELP = "help"
    const val CONTACT = "contact"
    const val TERMS = "terms"
    const val PRIVACY = "privacy"

    fun clubDetail(clubId: Int) = "clubs/$clubId"
    fun venueDetail(venueId: Int) = "venues/$venueId"
    fun playerDetail(playerId: Int) = "players/$playerId"
    fun matchDetail(matchId: Int) = "matches/$matchId"
    fun matchChat(matchId: Int) = "chat/$matchId"
}
